modLoader = "javafml" #mandatory
loaderVersion = "[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/alRex-U/LockOn/issues" #optional
[[mods]] #mandatory
modId = "lockon" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Lock<*>On" #mandatory
displayURL = "https://github.com/alRex-U/LockOn" #optional
logoFile = "../lockon_logo.png" #optional
credits = "Thanks for Minecraft, Java and Forge developpers" #optional
authors = "alRex_U" #optional
description = '''
This allows players to lock-on entities or points
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.lockon]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[32,)" #mandatory
ordering = "NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side = "CLIENT"
# Here's another dependency
[[dependencies.lockon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "CLIENT"
